name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /opt/trackimmo
          systemctl stop trackimmo-api
          git pull origin main
          source venv/bin/activate
          pip install prometheus_client requests beautifulsoup4 pandas playwright
          systemctl start trackimmo-api
          sleep 15
          curl -f http://localhost:8000/health