name: TrackImmo API Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn supabase pydantic-settings
        pip install pytest pytest-asyncio httpx
        
    - name: Test imports
      run: |
        python -c "import fastapi; print('FastAPI OK')"
        python -c "import supabase; print('Supabase OK')"
        
    - name: Basic syntax check
      run: |
        python -m py_compile trackimmo/app.py
        python -m py_compile trackimmo/config.py
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /opt/trackimmo
          
          # Pull latest changes
          git pull origin main
          
          # Activate virtual environment and install dependencies
          source venv/bin/activate
          pip install --upgrade pip
          pip install fastapi uvicorn supabase pydantic-settings
          
          # Create missing files if needed
          mkdir -p trackimmo/api trackimmo/utils tests
          
          # Check if main files exist, if not create basic structure
          if [ ! -f trackimmo/api/__init__.py ]; then
            echo '"""API package for TrackImmo."""' > trackimmo/api/__init__.py
          fi
          
          if [ ! -f trackimmo/utils/__init__.py ]; then
            echo '"""Utilities package for TrackImmo."""' > trackimmo/utils/__init__.py
          fi
          
          # Test configuration
          python3 -c "from trackimmo.config import settings; print('Config OK')"
          
          # Restart API service
          sudo systemctl daemon-reload
          sudo systemctl restart trackimmo-api
          
          # Wait and check service
          sleep 5
          sudo systemctl status trackimmo-api
          
          # Test API health
          curl -f http://localhost:8000/health || echo "API health check failed"